services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - custom

  test_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: test_postgres
      POSTGRES_DB: test_postgres
    ports:
      - "5433:5432"
    expose:
      - 5433
    networks:
      - custom

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend/src:/backend/src
      - ./backend/.env:/backend/.env
    working_dir: /backend/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge
