"""stock

Revision ID: 14bc1f624a47
Revises: 2ea101fb679d
Create Date: 2025-05-06 08:08:28.741106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bc1f624a47'
down_revision: Union[str, None] = '2ea101fb679d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties')),
    sa.UniqueConstraint('inn', name=op.f('uq_counterparties_inn'))
    )
    op.create_index(op.f('ix_counterparties_id'), 'counterparties', ['id'], unique=False)
    op.drop_constraint('fk_stock_moves_item_type_id_nomenclature_types', 'stock_moves', type_='foreignkey')
    op.drop_column('stock_moves', 'item_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_moves', sa.Column('item_type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_stock_moves_item_type_id_nomenclature_types', 'stock_moves', 'nomenclature_types', ['item_type_id'], ['id'])
    op.drop_index(op.f('ix_counterparties_id'), table_name='counterparties')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
