"""Create tables Recipe, Ingredient, Nomenclature, NomUnit, NomType, NomGroup

Revision ID: 008289dc4f7c
Revises: 6318f8c97929
Create Date: 2025-04-22 19:52:03.978264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3'
down_revision: Union[str, None] = '2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measure_units')),
    sa.UniqueConstraint('name', name=op.f('uq_measure_units_name')),
    sa.UniqueConstraint('short_name', name=op.f('uq_measure_units_short_name'))
    )
    op.create_table('nomenclature_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nomenclature_groups.id'], name=op.f('fk_nomenclature_groups_parent_id_nomenclature_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomenclature_groups')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_nomenclature_group_parent_name')
    )
    op.create_index(op.f('ix_nomenclature_groups_parent_id'), 'nomenclature_groups', ['parent_id'], unique=False)
    op.create_table('nomenclature_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomenclature_types')),
    sa.UniqueConstraint('name', name=op.f('uq_nomenclature_types_name'))
    )
    op.create_table('nomenclatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('measure_unit_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['nomenclature_groups.id'], name=op.f('fk_nomenclatures_group_id_nomenclature_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['measure_unit_id'], ['measure_units.id'], name=op.f('fk_nomenclatures_measure_unit_id_measure_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['nomenclature_types.id'], name=op.f('fk_nomenclatures_type_id_nomenclature_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nomenclatures')),
    sa.UniqueConstraint('barcode', name=op.f('uq_nomenclatures_barcode')),
    sa.UniqueConstraint('group_id', 'name', name='uq_nomenclature_group_name'),
    sa.UniqueConstraint('sku', name=op.f('uq_nomenclatures_sku'))
    )
    op.create_index(op.f('ix_nomenclatures_group_id'), 'nomenclatures', ['group_id'], unique=False)
    op.create_index(op.f('ix_nomenclatures_measure_unit_id'), 'nomenclatures', ['measure_unit_id'], unique=False)
    op.create_index(op.f('ix_nomenclatures_type_id'), 'nomenclatures', ['type_id'], unique=False)
    op.create_table('nomenclature_base_recipe_association',
    sa.Column('base_recipe_id', sa.UUID(), nullable=False),
    sa.Column('nomenclature_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['base_recipe_id'], ['base_recipes.id'], name=op.f('fk_nomenclature_base_recipe_association_base_recipe_id_base_recipes')),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclatures.id'], name=op.f('fk_nomenclature_base_recipe_association_nomenclature_id_nomenclatures')),
    sa.PrimaryKeyConstraint('base_recipe_id', 'nomenclature_id', name=op.f('pk_nomenclature_base_recipe_association'))
    )
    op.create_table('recipes',
    sa.Column('base_recipe_id', sa.UUID(), nullable=False),
    sa.Column('nomenclature_id', sa.UUID(), nullable=False),
    sa.Column('batch_amount', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('commentary', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['base_recipe_id'], ['base_recipes.id'], name=op.f('fk_recipes_base_recipe_id_base_recipes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_recipes_document_type_id_document_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclatures.id'], name=op.f('fk_recipes_nomenclature_id_nomenclatures'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('name', 'document_number', name='_unique_recipe_name_number_uc')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('nomenclature_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclatures.id'], name=op.f('fk_ingredients_nomenclature_id_nomenclatures'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.alter_column('base_recipes', 'commentary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint('_unique_name_number_uc', 'base_recipes', type_='unique')
    op.create_unique_constraint('_unique_base_recipe_name_number_uc', 'base_recipes', ['name', 'document_number'])
    op.drop_constraint('fk_document_number_counters_document_type_id_document_types', 'document_number_counters', type_='foreignkey')
    op.create_foreign_key(op.f('fk_document_number_counters_document_type_id_document_types'), 'document_number_counters', 'document_types', ['document_type_id'], ['id'], ondelete='RESTRICT')
    op.create_table('recipe_generation_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_formers_group_id', sa.UUID(), nullable=True),
    sa.Column('pigments_group_id', sa.UUID(), nullable=True),
    sa.Column('fillers_group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['film_formers_group_id'], ['nomenclature_groups.id'], name=op.f(
        'fk_recipe_generation_settings_film_formers_group_id_nomenclature_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fillers_group_id'], ['nomenclature_groups.id'], name=op.f(
        'fk_recipe_generation_settings_fillers_group_id_nomenclature_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pigments_group_id'], ['nomenclature_groups.id'], name=op.f(
        'fk_recipe_generation_settings_pigments_group_id_nomenclature_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_generation_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_generation_settings')
    op.drop_constraint(op.f('fk_document_number_counters_document_type_id_document_types'), 'document_number_counters', type_='foreignkey')
    op.create_foreign_key('fk_document_number_counters_document_type_id_document_types', 'document_number_counters', 'document_types', ['document_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_unique_base_recipe_name_number_uc', 'base_recipes', type_='unique')
    op.create_unique_constraint('_unique_name_number_uc', 'base_recipes', ['name', 'document_number'])
    op.alter_column('base_recipes', 'commentary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_table('ingredients')
    op.drop_table('recipes')
    op.drop_table('nomenclature_base_recipe_association')
    op.drop_index(op.f('ix_nomenclatures_type_id'), table_name='nomenclatures')
    op.drop_index(op.f('ix_nomenclatures_measure_unit_id'), table_name='nomenclatures')
    op.drop_index(op.f('ix_nomenclatures_group_id'), table_name='nomenclatures')
    op.drop_table('nomenclatures')
    op.drop_table('nomenclature_types')
    op.drop_index(op.f('ix_nomenclature_groups_parent_id'), table_name='nomenclature_groups')
    op.drop_table('nomenclature_groups')
    op.drop_table('measure_units')
    # ### end Alembic commands ###
