"""ondelete in association table

Revision ID: 9ad0632a4678
Revises: 6
Create Date: 2025-04-26 10:47:15.659583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad0632a4678'
down_revision: Union[str, None] = '6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_nomenclature_base_recipe_association_nomenclature_id_e299', 'nomenclature_base_recipe_association', type_='foreignkey')
    op.drop_constraint('fk_nomenclature_base_recipe_association_base_recipe_id__0dbf', 'nomenclature_base_recipe_association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_nomenclature_base_recipe_association_base_recipe_id_base_recipes'), 'nomenclature_base_recipe_association', 'base_recipes', ['base_recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_nomenclature_base_recipe_association_nomenclature_id_nomenclatures'), 'nomenclature_base_recipe_association', 'nomenclatures', ['nomenclature_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_nomenclature_base_recipe_association_nomenclature_id_nomenclatures'), 'nomenclature_base_recipe_association', type_='foreignkey')
    op.drop_constraint(op.f('fk_nomenclature_base_recipe_association_base_recipe_id_base_recipes'), 'nomenclature_base_recipe_association', type_='foreignkey')
    op.create_foreign_key('fk_nomenclature_base_recipe_association_base_recipe_id__0dbf', 'nomenclature_base_recipe_association', 'base_recipes', ['base_recipe_id'], ['id'])
    op.create_foreign_key('fk_nomenclature_base_recipe_association_nomenclature_id_e299', 'nomenclature_base_recipe_association', 'nomenclatures', ['nomenclature_id'], ['id'])
    # ### end Alembic commands ###
