"""add stock balance view

Revision ID: a00f9e851f01
Revises: fee7041cb4d2
Create Date: 2025-05-05 05:34:55.329493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'a00f9e851f01'
down_revision: Union[str, None] = 'fee7041cb4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_stock_balance = PGView(
        schema="public",
        signature="stock_balance",
        definition='SELECT m.nomenclature_id, n.type_id AS item_type_id, SUM(m.qty) AS balance\n    FROM stock_moves m\n    JOIN nomenclatures n ON n.id = m.nomenclature_id\n    GROUP BY m.nomenclature_id, n.type_id'
    )
    op.create_entity(public_stock_balance)

    public_get_stock_balance = PGFunction(
        schema="public",
        signature="get_stock_balance(p_nomenclature_id uuid)",
        definition='RETURNS numeric AS $$\n    SELECT COALESCE(SUM(qty), 0)\n      FROM stock_moves\n     WHERE nomenclature_id = p_nomenclature_id;\n    $$ LANGUAGE SQL STABLE'
    )
    op.create_entity(public_get_stock_balance)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_get_stock_balance = PGFunction(
        schema="public",
        signature="get_stock_balance(p_nomenclature_id uuid)",
        definition='RETURNS numeric AS $$\n    SELECT COALESCE(SUM(qty), 0)\n      FROM stock_moves\n     WHERE nomenclature_id = p_nomenclature_id;\n    $$ LANGUAGE SQL STABLE'
    )
    op.drop_entity(public_get_stock_balance)

    public_stock_balance = PGView(
        schema="public",
        signature="stock_balance",
        definition='SELECT m.nomenclature_id, n.type_id AS item_type_id, SUM(m.qty) AS balance\n    FROM stock_moves m\n    JOIN nomenclatures n ON n.id = m.nomenclature_id\n    GROUP BY m.nomenclature_id, n.type_id'
    )
    op.drop_entity(public_stock_balance)

    # ### end Alembic commands ###
