"""stock

Revision ID: fee7041cb4d2
Revises: 9ad0632a4678
Create Date: 2025-05-05 05:06:48.288923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee7041cb4d2'
down_revision: Union[str, None] = '9ad0632a4678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('commentary', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_documents_document_type_id_document_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('document_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('nomenclature_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_lines_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclatures.id'], name=op.f('fk_document_lines_nomenclature_id_nomenclatures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_lines')),
    sa.UniqueConstraint('document_id', 'nomenclature_id', name='uq_docline_nom')
    )
    op.create_table('stock_moves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_line_id', sa.UUID(), nullable=False),
    sa.Column('nomenclature_id', sa.UUID(), nullable=False),
    sa.Column('item_type_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('document_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_line_id'], ['document_lines.id'], name=op.f('fk_stock_moves_document_line_id_document_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['nomenclature_types.id'], name=op.f('fk_stock_moves_item_type_id_nomenclature_types')),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclatures.id'], name=op.f('fk_stock_moves_nomenclature_id_nomenclatures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_moves')),
    sa.UniqueConstraint('document_line_id', name=op.f('uq_stock_moves_document_line_id'))
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_moves')
    op.drop_table('document_lines')
    op.drop_table('documents')
    # ### end Alembic commands ###
